import React from 'react'
import { Html, Head, Main, NextScript, Script } from 'next/document'
export default function Document() {
  return (
    <Html lang="en">
      <Head>
        <title>Sirpi</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body>
       <Main>
        
       </Main>
       <NextScript/> 
      </body>
    </Html>
  )
}
